version: '2'

services:
  site:
    image: gtdev87/themostgreg-site
    labels:
      kompose.volume.size: 5Gi
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      WORKER_CONNECTIONS: 1024
    volumes:
      - webapp_files:/webapp:rw

  nginx:
    image: gtdev87/themostgreg-nginx
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NGINX_PORT=8000
    volumes_from:
      - site
    volumes:
      - webapp_files:/webapp:ro
    depends_on:
      - site

